package com.ustc.model;

import com.ustc.model.User;
import com.ustc.model.UserExample;
import java.util.List;

public interface UserDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Fri Apr 22 17:04:12 CST 2016
     */
    int countByExample(UserExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Fri Apr 22 17:04:12 CST 2016
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Fri Apr 22 17:04:12 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Fri Apr 22 17:04:12 CST 2016
     */
    void insert(User record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Fri Apr 22 17:04:12 CST 2016
     */
    void insertSelective(User record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Fri Apr 22 17:04:12 CST 2016
     */
    List selectByExample(UserExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Fri Apr 22 17:04:12 CST 2016
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Fri Apr 22 17:04:12 CST 2016
     */
    int updateByExampleSelective(User record, UserExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Fri Apr 22 17:04:12 CST 2016
     */
    int updateByExample(User record, UserExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Fri Apr 22 17:04:12 CST 2016
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Fri Apr 22 17:04:12 CST 2016
     */
    int updateByPrimaryKey(User record);
}